### ISSUE TITLE
Problem after reconnect

### ISSUE THREAD

**Issue by vadim-shadrin** [tarantool/tarantool-python#177] opened 2020-10-16 10:47 UTC
File "/usr/local/lib/python3.8/site-packages/tarantool/connection.py", line 380, in call
api-flask-v1_1  |     response = self._send_request(request)
api-flask-v1_1  |   File "/usr/local/lib/python3.8/site-packages/tarantool/connection.py", line 348, in _send_request
api-flask-v1_1  |     return self._send_request_wo_reconnect(request)
api-flask-v1_1  |   File "/usr/local/lib/python3.8/site-packages/tarantool/connection.py", line 263, in _send_request_wo_reconnect
api-flask-v1_1  |     response = Response(self, self._read_response())
api-flask-v1_1  |   File "/usr/local/lib/python3.8/site-packages/tarantool/response.py", line 67, in __init__
api-flask-v1_1  |     self._sync = header.get(IPROTO_SYNC, 0)
api-flask-v1_1  | AttributeError: 'int' object has no attribute 'get'

**Comment by memclutter** [comment] 2021-04-04 20:06
Same problem

**Comment by Totktonada** [comment] 2021-04-05 02:25
Looks like a problem around navigation within the msgpack stream. However I don't see an obvious problem in the code. How can I reproduce the issue?

**Comment by memclutter** [comment] 2021-04-12 21:16
> Looks like a problem around navigation within the msgpack stream. However I don't see an obvious problem in the code. How can I reproduce the issue?

make very many requests

**Comment by memclutter** [comment] 2021-04-12 21:56
I found the problem, I used one instance of the `Connection` in different threads, I create separate instances in each thread and the problem was solved :) @vadim-shadrin I hope this help you)

**Comment by Totktonada** [comment] 2021-04-12 22:10
@memclutter Thanks for spotting the problem!

The README warns about this:

> This driver is synchronous, so connection mustn't be shared between threads/processes.

**Comment by Totktonada** [comment] 2021-12-14 15:19
Closing as invalid so.

**Closed by Totktonada** 2021-12-14 15:19 UTC
Labels: bug, invalid
