### ISSUE TITLE
DeprecationWarning: decodestring() is a deprecated alias

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool-python#117] opened 2019-03-05 13:20 UTC
When running tests with pytest that use tarantool-python, I see the following warning:

```sh
  /usr/local/lib/python3.7/site-packages/tarantool/utils.py:88: DeprecationWarning: decodestring() is a deprecated alias since Python 3.1, use decodebytes()
    result.salt = base64.decodestring(greeting_buf[64:])[:20]
```

**Comment by Totktonada** [comment] 2019-03-05 21:54
Duplicate of #114.

**Closed by Totktonada** 2019-03-05 21:54 UTC
